### ISSUE TITLE
Ubuntu 16.04 LTS, screens (pygame, psychopy, expyriment) do not start

### ISSUE THREAD

**Issue by behinger** [smathot/OpenSesame#475] opened 2016-10-20 09:53 UTC
I'm using Ubuntu 16.04 LTS. When I start the default 'getting_started' experiment (tested with psychopy, pygame and expyriment) different crashes happen. I then have to kill the process. On expyriment, here the "starting experiment" screen appears, but then freezes. On normal psychopy and pygame they both freeze in a black screen. If I use the newest version of psychopy it 'finishes' with: 'The experiment finished successfully' or shows an error if I deactivate surpress warnings
#### Psychopy

I do not have administrative rights on the computer, opensesame was installed using the cogsci.nl repository. I updated all packages using virtualenv. I had to update pyglet to deactivate the psychopy 'surpress warnings'. before the update of pyglet the [ati radion X bug](https://github.com/cledio66/pyglet/issues/473) appeared.

without venv (surpress warnings is on, as per default)

```
Starting experiment as ExperimentProcess-1
openexp._canvas.psycho.init_display(): waitblanking = True
openexp._canvas.psycho.init_display(): monitor = testMonitor
openexp._canvas.psycho.init_display(): screen = 0
openexp.sampler._legacy.init_sound(): sampling freq = 48000, buffer size = 1024
```

```
psychopy.__version__
Out[2]: '1.83.04'
```

Screen stays black.

with venv things get more interesting. With surpressed warnings:

```
Starting experiment as ExperimentProcess-1
openexp._canvas.psycho.init_display(): waitblanking = True
openexp._canvas.psycho.init_display(): monitor = testMonitor
openexp._canvas.psycho.init_display(): screen = 0
openexp.sampler._legacy.init_sound(): sampling freq = 48000, buffer size = 1024
openexp.sampler._legacy.init_sound(): mixer already initialized, closing
```

Screen stays black.

Deactivating surpressed warnings:

```
Starting experiment as ExperimentProcess-1
openexp._canvas.psycho.init_display(): waitblanking = True
openexp._canvas.psycho.init_display(): monitor = testMonitor
openexp._canvas.psycho.init_display(): screen = 0

Unexpected error

item-stack: 
exception message: Could not create GL context
time: Thu Oct 20 11:34:59 2016
exception type: ContextException

Traceback:
  File "/usr/lib/python2.7/dist-packages/libqtopensesame/misc/process.py", line 140, in run
    exp.run()
  File "/usr/lib/python2.7/dist-packages/libopensesame/experiment.py", line 400, in run
    self.init_display()
  File "/usr/lib/python2.7/dist-packages/libopensesame/experiment.py", line 744, in init_display
    canvas.init_display(self)
  File "/usr/lib/python2.7/dist-packages/openexp/canvas.py", line 65, in init_display
    cls.init_display(experiment)
  File "/usr/lib/python2.7/dist-packages/openexp/_canvas/psycho.py", line 356, in init_display
    winType=u'pyglet', allowStencil=True)
  File "/net/store/nbp/users/behinger/tools/venv/lib/python2.7/site-packages/psychopy/visual/window.py", line 340, in __init__
    self._setupGL()
  File "/net/store/nbp/users/behinger/tools/venv/lib/python2.7/site-packages/psychopy/visual/window.py", line 1549, in _setupGL
    self._setupPyglet()
  File "/net/store/nbp/users/behinger/tools/venv/lib/python2.7/site-packages/psychopy/visual/window.py", line 1403, in _setupPyglet
    style=style)
  File "/net/store/nbp/users/behinger/tools/venv/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/net/store/nbp/users/behinger/tools/venv/lib/python2.7/site-packages/pyglet/window/__init__.py", line 516, in __init__
    context = config.create_context(gl.current_context)
  File "/net/store/nbp/users/behinger/tools/venv/lib/python2.7/site-packages/pyglet/gl/xlib.py", line 186, in create_context
    return XlibContextARB(self, share)
  File "/net/store/nbp/users/behinger/tools/venv/lib/python2.7/site-packages/pyglet/gl/xlib.py", line 296, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/net/store/nbp/users/behinger/tools/venv/lib/python2.7/site-packages/pyglet/gl/xlib.py", line 199, in __init__
    raise gl.ContextException('Could not create GL context')
ContextException: Could not create GL context
```

```
psychopy.__version__
Out[3]: '1.84.2'
```

Which is interesting, because in the same ipython console I can start a psychopy screen (using pyglet) with no problems and draw stimuli on it (I used [this example](http://www.psychopy.org/coder/tutorial1.html) and added the winType='pyglet option)
#### Pygame

without updated pygame

```
Starting experiment as ExperimentProcess-1
openexp._canvas.legacy.init_display(): enabling hardware surface
openexp._canvas.legacy.init_display(): enabling double buffering
openexp._canvas.legacy.init_display(): video mode ok
openexp.sampler._legacy.init_sound(): sampling freq = 48000, buffer size = 1024
openexp.sampler._legacy.init_sound(): mixer already initialized, closing
```

```
pygame.__version__
Out[2]: '1.9.1release'
```

with newest pygame in venv:

```
Starting experiment as ExperimentProcess-1
openexp._canvas.legacy.init_display(): enabling hardware surface
openexp._canvas.legacy.init_display(): enabling double buffering
openexp._canvas.legacy.init_display(): video mode ok
```

```
pygame.__version__
Out[4]: '1.9.1release'
```

Screen stays black
#### expyriment

I could only test this in venv. expyriment is not installed by default.

```
Starting experiment as ExperimentProcess-2
Expyriment 0.8.0 (Python 2.7.12) 
openexp.sampler._legacy.init_sound(): sampling freq = 48000, buffer size = 1024
```

```
import expyriment
Expyriment 0.8.0 (Python 2.7.12) 
```

Screen hangs at 'preparing experiment...'

Adding --debug to opensesame does not give anything related.

```
:~$ opensesame --version
3.1.2b1 'Jazzy James'
```

Maybe I missed something obvious? I could not really find out anything towards the pyglet openGL bug. I use a "Nvidia GeForce GTX 750 Ti" on this computer. It is only a development computer, not for running the experiment. Nvidia Driver Version 367.35.
I use a dual screen setup.

**Comment by smathot** [comment] 2016-11-02 12:37
Thanks for this elaborate issue report. I'm going to disappoint you though: I think there's a problem with the video card/ driver. This won't be easy (or even possible) to resolve, especially if you don't have admin rights. I suspect that all this weird behavior is related to one underlying video problem.

I will close this issue, because it's not a bug in the sense that I don't think there's something in OpenSesame that triggers this (or a change that could fix it).

What you could do is post this problem on the Expyriment or PsychoPy forum. They have much more experience with low-level video than I, and perhaps they have seen this kind of problem before. I wouldn't repost this issue on their GitHub issue tracker, because they may close it, feeling (quite rightly) that it's not an issue with the software itself.

- http://forum.cogsci.nl/categories/expyriment
- http://discourse.psychopy.org/

Sorry I cannot be more helpful!

PS. If this does turn out to be a problem with OpenSesame, I will re-open the issue.

**Closed by smathot** 2016-11-02 12:37 UTC
