### ISSUE TITLE
expyriment_tmp folder is never cleared

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#551] opened 2017-07-27 15:06 UTC
[Not sure if I should create this this issue in https://github.com/smathot/expyriment]

When using the *expyriment back-end* all visuals are pregenerated and stored in 
> C:\Users\[username]\AppData\Local\Temp\expyriment_tmp

This folder is never cleaned by OpenSesame. When a experiment has lots of stimuli (and might be a bit inefficiently programmed) multiple runs fill up the hard disk with thousands of files using hundreds of gigabytes.

The latest version of expyriment seems to have some functionality to [delete the temp folder](https://github.com/expyriment/expyriment/blob/master/expyriment/stimuli/defaults.py#L125), but I never used and/or tested this outside of OpenSesame.

I suppose appending a *delete the temp folder* function to the `cleanup_functions` would work when the *back-end* is *expyriment* but i wouldn't know where to do this.

**Comment by smathot** [comment] 2017-07-28 13:40
Hi Jarik,

Thanks for flagging this. This would indeed be an issue to post in the Expyriment repo (upstream though, not in my fork!) if it weren't for the fact that they've already fixed it in the latest version.

The reason that OpenSesame is still shipping an outdated version is that I don't like to update libraries during a maintenance release. However, 3.1 is now already a year old, so it might be good to bring all libraries up to date with the next maintenance release. But that also introduces a risk of regression, of course. I'll think about it.

But I'll close this one, because it's in any case not something to be fixed in OpenSesame.

Cheers!
Sebastiaan

**Closed by smathot** 2017-07-28 13:40 UTC

**Comment by JdenHartog** [comment] 2017-08-08 14:10
Hi Sebastiaan,

Ok, I assumed you were always making an "OpenSesame edition" 😃 because of the names *0.8.1.opensesame1* and *0.8.1.opensesame1* so I flagged this in your fork.

I tested this quickly with *opensesame_3.1.7-py2.7-win32-1.exe* using pip to --upgrade expyriment to 0.9.0, but it didn't solve the problem (only creates unique expyriment directories for every run).

But I can definitely imagine this isn't worth the hassle and the risk of regression anyway.

Best,
Jarik
