### ISSUE TITLE
Item disappears after cancelling its addition to a loop

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#313] opened 2015-03-18 14:28 UTC
When trying to drag an existing item into a loop in the overview area, I accidently chose the wrong item, so that I wanted to cancel this action and pressed respective option in the window that popped-up. However, this caused the item (and all its occurrences) to disappear completely from the experiment. It isn't in the "unused items" folder and can't be found at any other location. 
The OpenSesame version is 2.9.4 running on linux.

**Comment by smathot** [comment] 2015-03-18 17:03
Hi Eduard,

Thanks for spotting this one. It's actually already fixed in 2.9.5 (ea5ba03). Could you confirm that the issue is gone in the latest prerelease?

Cheers,
Sebastiaan

**Closed** 2015-04-16 14:45 UTC
