### ISSUE TITLE
Sketchpad items not shown at second run of experiment (Mac OS X, Jazzy James)

### ISSUE THREAD

**Issue by hedderik** [smathot/OpenSesame#481] opened 2016-11-15 16:48 UTC
Hi,

I'm encountering a weird, reproducible bug on Mac OS X (latest Mac OS, fully updated) using Jazzy James.

Attached is a simple script of an experiment in which participants are presented four loops (experimental blocks), and before, after and in between those loops we present sketchpad items with instructions. The first run after starting up OS, everything works as expected. The second run, however, the sketchpad items that are *in between* loops are shown as a completely white screen. If you just press a key to end that sketchpad display, the next loop starts and all sketchpad items in that loop are shown as expected.

When I move the sketchpad items to before the first loop, they are shown as expected. And when I close OS, and restart it, it works as expected. This problem was replicated on one of my colleague's macs (don't know the exact version of Mac OS X / OpenSesame on his mac). 

Any ideas about what might be causing this problem / how to resolve this?

  - hedderik.

@smathot asked me to include @dschreij in this message.

[cogmod2016.osexp.zip](https://github.com/smathot/OpenSesame/files/592598/cogmod2016.osexp.zip)

**Comment by smathot** [comment] 2016-11-16 08:34
I can sort of reproduce this as well on Ubuntu 16.04 with OpenSesame 3.1.3. However, I've seen the white screens only once; usually OpenSesame just crashes with a segmentation fault on the second run. It happens when using the xpyriment backend and the inprocess runner (which doesn't start a new process when running an experiment), but not when using another backend or the multiprocess runner.

So it seems to be a memory problem, a carry-over effect from one run to the next. 

@dschreij Maybe you monitor memory usage when running this experiment. Does memory fill up over time?

**Comment by dschreij** [comment] 2016-11-16 15:20
I can confirm this behaviour also shows on my machine, and only if the inprocess runner is selected. Moreover, I recently upgraded to MacOS Sierra, which also shows this _before the very first run_ of the experiment:

![screenshot 2016-11-16 11 16 03](https://cloud.githubusercontent.com/assets/689044/20352571/186b4744-abee-11e6-833d-62fca259c17c.png)

so something is not right in general. 

I doubt this is something that we can do about in OpenSesame and is caused by bad memory management by OpenSesame's underlying libraries as Sebastiaan suggested. The mention of sdlmain_osx.so in the stacktrace above is strongly indicative of this.

My advice is to just use the multiprocess runner instead of the inprocess runner. Multiprocess should work reliably now on OSX too, and makes sure an experiment starts with a clean slate of memory each time.

**Comment by smathot** [comment] 2016-11-23 16:00
@dschreij: on a related note, @hedderik just said that the experiments look funky with the legacy back-end, in that it doesn't show the white fixation dot and yellow circle (right?). For me, on Ubuntu, it looks fine though. Do you also see these problems with the legacy backend on Mac OS when running this experiment?

**Comment by dschreij** [comment] 2016-12-01 14:47
The experiment indeed appears to behave funky when being run in legacy mode, which doesn't happen when running the experiment in psychopy. I can see the yellow circle, but I don't see any fixation dots (running in multiprocessing mode). Additionally, the experiment seem to race through the blocks (as in, it doesn't pause where it should pause) and appears to skip displays.

Not good what's going on here...

**Comment by dschreij** [comment] 2016-12-01 15:15
Right, after having looked more closely at this, I have no clue... Other experiments seem to run fine with the legacy backend, so why this one is behaving so peculiar remains a riddle...

**Comment by smathot** [comment] 2016-12-01 16:16
From what you're describing, I'm guessing that the PyGame sleep function doesn't work. Could that explain all the symptoms? (That, of course, leaves open the question *why* the sleep function doesn't work.)

**Comment by dschreij** [comment] 2016-12-02 12:23
It surely seems like it, but that leaves the question why it doesn't work in this particular experiment, but does seem to work everywhere else. Additionally, on some displays it does sleep (mainly the when showing the yellow circle), but on others it doesn't (and skips them completely).

**Comment by dschreij** [comment] 2017-01-30 17:50
This weird behavior now also occurs for me with the Attentional Capture example experiment. I only see the stimulus display and the feedback display, but nothing in between (thus no fixation dot or placeholder display that precede the stimulus display). Everything seems to be in order, and everything runs fine in psychopy or expyriment, so I don't know what causes legacy to behave weird...

**Comment by dschreij** [comment] 2017-01-30 17:52
I must add, that pygame (or rather the underlying SDL libraries) are a mess in general on OS X these days, so I hope it's not outside our reach to fix this problem.

**Comment by smathot** [comment] 2017-02-08 08:27
I've just tested this a bit with the Mac OS package of OpenSesame 3.1.6, which Daniel built last night. (Thanks!) I can reproduce the white-screen issue, but it's resolved by selecting the multiprocess runner (under Preferences). I so far haven't experienced any strange behaviour or crashes with this new version.

@dschreij The inprocess runner is the default on Mac OS. Is there still any reason for this? It used to be necessary for the packaging process, right? But now that we're using a miniconda base, we may save ourselves a lot of headache by using multiprocess by default, as on other operating systems.

I will publicly release the new Mac OS package this morning.

**Comment by dschreij** [comment] 2017-02-10 14:58
No, this should be the multiprocess runner, since it works quite nicely with the anaconda-based package.

**Comment by smathot** [comment] 2020-04-29 08:16
Closing this because it's best addressed in #517 (if it's still current).

**Closed by smathot** 2020-04-29 08:16 UTC
Labels: Bug, Major
