### ISSUE TITLE
penwidth of canvas.line under psychopy limited to 10pt

### ISSUE THREAD

**Issue by eort** [smathot/OpenSesame#406] opened 2016-03-18 12:46 UTC
Not sure whether this is a bug or intended behaviour, but under the `PsychoPy` backend,  the width of a line doesn't increase further than ca. 10 pt. This is true for all functions that rely on canvas.line(), so canvas.rect() and canvas.line()

Attached a basic example. 

[lineDemo.osexp.zip](https://github.com/smathot/OpenSesame/files/179639/lineDemo.osexp.zip)

Eduard

**Comment by smathot** [comment] 2016-03-21 08:15
Hi Eduard,

This is definitely not intended behavior, but the problem seems to be in PsychoPy, which caps `lineWidth` values higher than 10. Right now, the implementation of `canvas.line()` uses `psychopy.visual.ShapeStim`. Possibly, `psychopy.visual.Line` doesn't have the same limitation. Would you mind looking in to this a bit further?

1. Does this limitation apply to both `ShapeStim` and `Line`?
2. Does this happen on all platforms. (I have tested it on Ubuntu 15.10, and so have you, I imagine?)

Cheers and thanks!  
Sebastiaan

**Comment by eort** [comment] 2016-03-22 12:40
It might take a little while, but I'll have a look. 


Eduard

**Comment by eort** [comment] 2016-07-13 08:21
Hi Sebastiaan, 

> Does this limitation apply to both `ShapeStim` and `Line`?

Yes, it does. `Line` inherits from `ShapeStim`,  so the `linewidth` has the same limitations for both

I suppose there is nothing to be done about that then?

Eduard

**Comment by smathot** [comment] 2016-07-13 10:15
Ok, let's close this one then. Maybe you can check if this issue is already on the PsychoPy issue tracker, and, if not, repost it there?

**Closed by smathot** 2016-07-13 10:15 UTC
Labels: Minor

**Comment by eort** [comment] 2016-07-13 10:28
Just checked. And indeed, there is already an issue on that. Ironically, it was opened by you 1.5 years ago. [Here](https://github.com/psychopy/psychopy/issues/818) the issue.

**Comment by smathot** [comment] 2016-07-13 10:58
Haha, I honestly don't remember that.
