### ISSUE TITLE
Out of memory error using large list with legacy back-end

### ISSUE THREAD

**Issue by JdenHartog** [smathot/OpenSesame#413] opened 2016-04-22 10:42 UTC
Giving technical support to a researcher we ran into an _Out of memory_ error when using the _legacy_ back-end. I isolated the problem in this experiment: [mem.txt](https://github.com/smathot/OpenSesame/files/231549/mem.txt) (please change .txt in .osexp extension). Basically I fill a list with 50 canvases in the prepare phase and show them in the run phase for 10 loop cycles. The problem seems to be that the memory isn't released (garbage isn't collected) and so an Out of memory error arises. In the screenshot of the Physical Memory Usage History in the Performance tab of the Windows Task Manager you can see the memory usage increasing on every sequence prepare. For the _xpyriment_ and _psycho_ back-ends the memory seems to be released during the execution of the exact same attached experiment.
![memory](https://cloud.githubusercontent.com/assets/8225621/14738394/899bdae8-0881-11e6-968c-4d017fa76ed0.png)
Because the researcher needed to use the legacy back-end, I kept searching and found a **workaround** for this problem: forcing garbage collect:

`import gc`
`gc.collect()`

Please note that _gc.collect()_ takes time (about 50 milliseconds in attached experiment) so make sure to add it in a separate inline at the end of the sequence. This way it should not interfere with timing of collecting responses after showing the canvases like one might do in a real experiment.

These test where run on a fresh Windows 7 64bit installation with opensesame_**3.0.7**-py2.7-win32-3.exe installed. The computer has 4GB of memory but I was also able to reproduce the problem on an 8GB computer. You might want to play around with the size of the list (50 in the attached experiment) to reproduce this problem on other hardware.

Best,
Jarik

**Comment by smathot** [comment] 2016-04-22 12:41
Hi Jarik,

Thanks for posting this here. It seems that we will need to manually call `gc.collect()` then, possibly at the end of the run phase of sequence items. We're going to look into it, and think about the best solution. In any case, it's really important, so thanks a lot!

Cheers,
Sebastiaan

**Comment by JdenHartog** [comment] 2016-04-22 14:55
Hi Sebastiaan,

You're welcome! I didn't realize this was a major thing also because I didn't find any related _Out of memory_ posts on the forum except for mine :-)
I did a quick test on the same hardware with OpenSesame 2.9.7 with 50 instead of 10 loop cycles to stress the system (see image below). As I expected garbage collection happens automatically. Though I don't know when and if it might affect timing in general. 

![mem3](https://cloud.githubusercontent.com/assets/8225621/14745009/84316050-08a9-11e6-9277-d7b0399e35bb.png)

Possibly gc.set_threshold() and the other functions at https://docs.python.org/2/library/gc.html are interesting to look at....

**Comment by smathot** [comment] 2016-05-01 11:58
I added a way to disable automatic garbage collection, by setting the `disable_garbage_collection` variable to 'yes'. (It is by default.) When gc is disabled, garbage collection is forced at the end of the run phase of each sequence. This should prevent memory from filling up, and also prevent garbage collection from occurring at time-critical moments, thus disrupting timing. The downside, of course, is that it adds a bit of lag at the end of each sequence, on the order of 50 - 100 ms.

Let's see if disabling gc has any adverse consequences. If not, I think we can disable it by default.

**Comment by smathot** [comment] 2016-05-28 15:57
I'm closing this, because I think the issue is resolved after 3b4c837, without any adverse consequences. Let's keep an eye out though.

**Closed by smathot** 2016-05-28 15:57 UTC
Labels: Major
