### ISSUE TITLE
opensesamerun not working after update to 3.1

### ISSUE THREAD

**Issue by EruIluvatar** [smathot/OpenSesame#435] opened 2016-07-18 07:56 UTC
Hi

After updating to 3.1, opensesamerun is not able to run any experiments, neither from CLI nor from GUI.
When Run is clicked (with Experiment and Subject number specified), the GUI just reopens itself with the same options.
The CLI also does not treat options like `--version` in a correct manner, it simply opens the GUI no matter what options are given.

Edit: OS is Win8.1, same in Win7

**Comment by smathot** [comment] 2016-07-19 10:53
Closing as a duplicate of #437.

**Closed by smathot** 2016-07-19 10:53 UTC
