### ISSUE TITLE
Psychopy backend right mouse-click ( button 3) raises IndexError (and expt crash)

### ISSUE THREAD

**Issue by wkruijne** [smathot/OpenSesame#425] opened 2016-06-10 13:19 UTC
Hey Sebastiaan,

See the title, and [this file for testing](http://www.filedropper.com/mousetesterpsycho) -- I think the issue lies in the psycho mouse-backend, line 59 in `get_click()`. There, the loop that polls the response is as follows:

```
		while True:
			time = self.experiment.clock.time()
			buttons, times = self.mouse.getPressed(getTime=True)
			for i in (1,2,3):
				if buttons[i-1] and (buttonlist is None or i-1 in buttonlist):
					button = i
					pos = self.mouse.getPos()
					time = times[i]
					break
			else:
				if timeout is not None and time-start_time >= timeout:
					break
				continue
			break
```
I think the line `time = times[i]` should be changed to `time=times[i-1]` like the statements above it.

Best,
W

**Comment by smathot** [comment] 2016-06-10 13:47
Hi Wouter,

Thanks! This seems to be a duplicate of #414 (closed), right? So I'll close this one, but let me know if it's not a duplicate.

Cheers,
Sebastiaan

**Closed by smathot** 2016-06-10 13:47 UTC

**Comment by wkruijne** [comment] 2016-06-10 14:02
Woops -- I thought just looking at the master branch was giving me the most up-to-date code -- yeah that fix should do it. Thanks!
W
